# Basic
title: YauzZ Profession
subtitle: 点点滴滴
welcome_message: 私人茶社，品茗小酌
# description: 
creator: <a href="http://blog.yauzz.com/">@yauzz</a>

url: "http://blog.yauzz.com/"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: yauzz
    github: yauzz
    twitter: yauzz
    gplus: 
    mail: yauzz.scu@gmail.com

# Google Analytics
ga:
    id: 59502141
    host: blog.yauzz.com
